apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  secret_key: {{ .Values.secret_key | b64enc }}
  db_user: {{ .Values.postgres.username | b64enc }}
  db_password: {{ .Values.postgres.password | b64enc }}
  db_name: {{ .Values.postgres.database | b64enc }}
  db_host: {{ .Values.postgres.host | b64enc }}
  db_port: {{ .Values.postgres.port | b64enc }}