apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envSecretName }}
type: Opaque
data:
  secret_key: {{ .Values.secret_key | default "" | b64enc }}
  db_host: {{ .Values.db_host | default "" | b64enc }}
  db_user: {{ .Values.db_user | default "" | b64enc }}
  db_password: {{ .Values.db_password | default "" | b64enc }}
  db_name: {{ .Values.db_name | default "" | b64enc }}
